language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
matrix:
    allow_failures:
        - "3.3"
        - "3.4"
        - "3.5"
        - "3.6"
script: python setup.py test
